<Project>
	<PropertyGroup>
		<Copyright>Copyright (C) 2026 ColorVision Corporation</Copyright>
		<AssemblyCompany>ColorVision Corp.</AssemblyCompany>
		<AssemblyCopyright>Copyright (C) 2026 ColorVision Corporation</AssemblyCopyright>
		<AssemblyProduct>ColorVision</AssemblyProduct>
		<Company>ColorVision</Company>
		<NeutralLanguage>zh-CN</NeutralLanguage>
	</PropertyGroup>
</Project>  