<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.9.0.20240103" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.9.0.20240103" />
    <PackageReference Include="WindowsAPICodePack" Version="8.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\CVWindowsService\CV.DBEntities\CV.DBEntities.csproj" />
    <ProjectReference Include="..\CVDB\CVDB.csproj" />
    <ProjectReference Include="..\CVWaferProber.Core\CVWaferProber.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CVCommCore">
      <HintPath>..\DLL\CVCommCore.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
