<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.11.0.20250507" />
		<PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
		<PackageReference Include="ScottPlot.WPF" Version="5.0.56" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CVDB\CVDB.csproj" />
		<ProjectReference Include="..\CVWaferProber.Core\CVWaferProber.Core.csproj" />
		<ProjectReference Include="..\CVWPFSpectrumControl\CVWPFSpectrumControl.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="CV.DBEntities">
			<HintPath>..\DLL\CV.DBEntities.dll</HintPath>
		</Reference>
		<Reference Include="CVCommCore">
			<HintPath>..\DLL\CVCommCore.dll</HintPath>
		</Reference>
		<Reference Include="WaferComm.Core">
		  <HintPath>..\DLL\WaferComm.Core.dll</HintPath>
		</Reference>
	</ItemGroup>
	<!-- 启用WinForm兼容，引入WindowsFormsIntegration --><!--
	<PropertyGroup>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	--><!-- 显式引用WindowsFormsIntegration程序集 --><!--
	<ItemGroup>
		<FrameworkReference Include="Microsoft.WindowsDesktop.App.WindowsForms" />
	</ItemGroup>-->
</Project>
