<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome6.Fonts" Version="2.5.1" />
    <PackageReference Include="OpenCvSharp4" Version="4.9.0.20240103" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.9.0.20240103" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.9.0.20240103" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CVWaferProber.Core\CVWaferProber.Core.csproj" />
  </ItemGroup>

</Project>
