<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
    <UseWindowsForms>True</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyVersion>2026.02.03.0</AssemblyVersion>
    <FileVersion>2026.02.03.0</FileVersion>
    <Company>ColorVision</Company>
    <Copyright>Copyright © 2026 视彩光电</Copyright>
    <ApplicationIcon>LOG.ico</ApplicationIcon>
    <PackageIcon>LOG.ico</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resources\**" />
    <EmbeddedResource Remove="Resources\**" />
    <None Remove="Resources\**" />
    <Page Remove="Resources\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="en-US\ST.Library.UI.resources.dll" />
    <None Remove="Views\LOG.ico" />
    <None Remove="zh-CN\ST.Library.UI.resources.dll" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChipMapping\ChipMapping.csproj" />
    <ProjectReference Include="..\CVAVMControl\CVVAMControl.csproj" />
    <ProjectReference Include="..\CVDB\CVDB.csproj" />
    <ProjectReference Include="..\CVMQTTClient\CVMQTTClient.csproj" />
    <ProjectReference Include="..\CVWaferProber.Core\CVWaferProber.Core.csproj" />
    <ProjectReference Include="..\CVWPFCamImageCtrl\CVWPFCamImageCtrl.csproj" />
    <ProjectReference Include="..\CVWPFSpectrometerCtrl\CVWPFSpectrometerCtrl.csproj" />
    <ProjectReference Include="..\WaferProberClient\WaferComm.Client\WaferComm.Client.csproj" />
    <ProjectReference Include="..\WaferProberClient\WaferComm.Core\WaferComm.Core.csproj" />
    <ProjectReference Include="..\WaferProberClient\WaferComm.Processors\WaferComm.Processors.csproj" />
    <ProjectReference Include="..\WaferProberClient\WaferComm.StateMachine\WaferComm.StateMachine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="log4net" Version="2.0.17" />
    <PackageReference Include="MQTTnet" Version="4.3.5.1141" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
    <PackageReference Include="System.Management" Version="10.0.0" />
    <PackageReference Include="System.Reactive" Version="6.0.2" />
  </ItemGroup>
  <ItemGroup>
    <!-- 指定要包含的 DLL -->
    <Content Include="..\DLL\CV_algorithm.dll">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\DLL\opencv_world401.dll">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content> 
    <Content Include="..\ScanData_sc.csv">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content> 
    <Content Include="en-US\ST.Library.UI.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content> 
    <Content Include="LOG.ico" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="CV.DBEntities">
      <HintPath>..\DLL\CV.DBEntities.dll</HintPath>
    </Reference>
    <Reference Include="CVCommCore">
      <HintPath>..\DLL\CVCommCore.dll</HintPath>
    </Reference>
    <Reference Include="CVMQTTLib">
      <HintPath>..\DLL\CVMQTTLib.dll</HintPath>
    </Reference>
    <Reference Include="CVMysqlLib">
      <HintPath>..\DLL\CVMysqlLib.dll</HintPath>
    </Reference>
    <Reference Include="FlowEngineLib">
      <HintPath>..\DLL\FlowEngineLib.dll</HintPath>
    </Reference>
    <Reference Include="HandyControl">
      <HintPath>..\DLL\FlowEngineLib.dll\HandyControl.dll</HintPath>
    </Reference>
    <Reference Include="ST.Library.UI">
      <HintPath>..\DLL\ST.Library.UI.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="zh-CN\ST.Library.UI.resources.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="cfg\MQTT.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="cfg\MySql.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Img\LOG.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="LOG.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Img\LOG.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
