<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAot>true</PublishAot>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <!-- 在此处固定 RID -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WaferComm.Core\WaferComm.Core.csproj" />
  </ItemGroup>

</Project>
